# Generated by Django 3.2.14 on 2023-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_column='message')),
                ('date', models.DateTimeField(db_column='date')),
            ],
            options={
                'db_table': 'Chat',
                'managed': False,
            },
        ),
    ]
