# Generated by Django 3.2.14 on 2023-06-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('report_message', models.TextField(db_column='report_message')),
                ('date', models.DateTimeField(db_column='report_date')),
                ('log', models.TextField(db_column='log')),
            ],
            options={
                'db_table': 'Reports',
                'managed': False,
            },
        ),
    ]
