# Generated by Django 3.2.14 on 2023-05-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compositekey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompositeKey',
        ),
    ]
