# Generated by Django 3.2.14 on 2023-06-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reports'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chat_history',
        ),
    ]
