# Generated by Django 4.1.7 on 2023-06-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chat_history',
        ),
    ]
